# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8099
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

# 用户组 可配置多个用户
users:
    userConfigs:
      - loginName: admin
        password: 123456
      - loginName: admin1
        password: 666666
      - loginName: admin2
        password: 123456

# 系统配置
system:
  title: xxx数据系统
  remark: xxx版权所有

